name: cow
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - cairo=1.16.0
  - certifi=2020.6.20
  - cudatoolkit=10.2.89
  - dbus=1.13.18
  - expat=2.2.10
  - ffmpeg=4.0
  - fontconfig=2.13.1
  - freeglut=3.0.0
  - freetype=2.10.4
  - glib=2.66.1
  - graphite2=1.3.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - intel-openmp=2020.2
  - jasper=2.0.14
  - jpeg=9b
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran=3.0.0
  - libglu=9.0.0
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - ninja=1.10.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.1.1h
  - pcre=8.44
  - pillow=8.0.0
  - pip=20.2.4
  - pixman=0.38.0
  - pthread-stubs=0.4
  - py-opencv=3.4.2
  - pyqt=5.9.2
  - python=3.7.9
  - python_abi=3.7
  - pytorch=1.6.0
  - qt=5.9.7
  - readline=8.0
  - setuptools=50.3.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - torchvision=0.7.0
  - wheel=0.35.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - pyfakewebcam==0.1.0
